#include <golos/protocol/get_config.hpp>
#include <golos/protocol/config.hpp>
#include <golos/protocol/asset.hpp>
#include <golos/protocol/version.hpp>

namespace golos {
    namespace protocol {

        fc::variant_object get_config() {
            fc::mutable_variant_object result;

            result["STEEMIT_100_PERCENT"] = STEEMIT_100_PERCENT;
            result["STEEMIT_1_PERCENT"] = STEEMIT_1_PERCENT;
            result["STEEMIT_ADDRESS_PREFIX"] = STEEMIT_ADDRESS_PREFIX;
            result["STEEMIT_BANDWIDTH_AVERAGE_WINDOW_SECONDS"] = STEEMIT_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
            result["STEEMIT_BANDWIDTH_PRECISION"] = STEEMIT_BANDWIDTH_PRECISION;
            result["BLOCKCHAIN_HARDFORK_VERSION"] = BLOCKCHAIN_HARDFORK_VERSION;
            result["BLOCKCHAIN_VERSION"] = BLOCKCHAIN_VERSION;
            result["STEEMIT_BLOCK_INTERVAL"] = STEEMIT_BLOCK_INTERVAL;
            result["STEEMIT_BLOCKS_PER_DAY"] = STEEMIT_BLOCKS_PER_DAY;
            result["STEEMIT_BLOCKS_PER_YEAR"] = STEEMIT_BLOCKS_PER_YEAR;
            result["STEEMIT_CASHOUT_WINDOW_SECONDS"] = STEEMIT_CASHOUT_WINDOW_SECONDS;
            result["STEEMIT_CHAIN_ID"] = STEEMIT_CHAIN_ID;
            result["STEEMIT_GENESIS_TIME"] = STEEMIT_GENESIS_TIME;
            result["STEEMIT_HARDFORK_REQUIRED_WITNESSES"] = STEEMIT_HARDFORK_REQUIRED_WITNESSES;
            result["STEEMIT_INIT_MINER_NAME"] = STEEMIT_INIT_MINER_NAME;
            result["STEEMIT_INIT_PUBLIC_KEY_STR"] = STEEMIT_INIT_PUBLIC_KEY_STR;
            result["STEEMIT_INIT_SUPPLY"] = STEEMIT_INIT_SUPPLY;
            result["STEEMIT_IRREVERSIBLE_THRESHOLD"] = STEEMIT_IRREVERSIBLE_THRESHOLD;
            result["STEEMIT_MAX_ACCOUNT_NAME_LENGTH"] = STEEMIT_MAX_ACCOUNT_NAME_LENGTH;
            result["STEEMIT_MAX_ACCOUNT_WITNESS_VOTES"] = STEEMIT_MAX_ACCOUNT_WITNESS_VOTES;
            result["STEEMIT_MAX_BLOCK_SIZE"] = STEEMIT_MAX_BLOCK_SIZE;
            result["STEEMIT_MAX_COMMENT_DEPTH"] = STEEMIT_MAX_COMMENT_DEPTH;
            result["STEEMIT_MAX_MEMO_SIZE"] = STEEMIT_MAX_MEMO_SIZE;
            result["STEEMIT_MAX_WITNESSES"] = STEEMIT_MAX_WITNESSES;
            result["STEEMIT_MAX_MINER_WITNESSES"] = STEEMIT_MAX_MINER_WITNESSES;
            result["STEEMIT_MAX_PROXY_RECURSION_DEPTH"] = STEEMIT_MAX_PROXY_RECURSION_DEPTH;
            result["STEEMIT_MAX_RESERVE_RATIO"] = STEEMIT_MAX_RESERVE_RATIO;
            result["STEEMIT_MAX_RUNNER_WITNESSES"] = STEEMIT_MAX_RUNNER_WITNESSES;
            result["STEEMIT_MAX_SHARE_SUPPLY"] = STEEMIT_MAX_SHARE_SUPPLY;
            result["STEEMIT_MAX_SIG_CHECK_DEPTH"] = STEEMIT_MAX_SIG_CHECK_DEPTH;
            result["STEEMIT_MAX_TIME_UNTIL_EXPIRATION"] = STEEMIT_MAX_TIME_UNTIL_EXPIRATION;
            result["STEEMIT_MAX_TRANSACTION_SIZE"] = STEEMIT_MAX_TRANSACTION_SIZE;
            result["STEEMIT_MAX_UNDO_HISTORY"] = STEEMIT_MAX_UNDO_HISTORY;
            result["STEEMIT_MAX_VOTE_CHANGES"] = STEEMIT_MAX_VOTE_CHANGES;
            result["STEEMIT_MAX_VOTED_WITNESSES"] = STEEMIT_MAX_VOTED_WITNESSES;
            result["STEEMIT_MAX_WITHDRAW_ROUTES"] = STEEMIT_MAX_WITHDRAW_ROUTES;
            result["STEEMIT_MAX_WITNESS_URL_LENGTH"] = STEEMIT_MAX_WITNESS_URL_LENGTH;
            result["STEEMIT_MIN_ACCOUNT_CREATION_FEE"] = STEEMIT_MIN_ACCOUNT_CREATION_FEE;
            result["STEEMIT_MIN_ACCOUNT_NAME_LENGTH"] = STEEMIT_MIN_ACCOUNT_NAME_LENGTH;
            result["STEEMIT_MIN_BLOCK_SIZE_LIMIT"] = STEEMIT_MIN_BLOCK_SIZE_LIMIT;
            result["STEEMIT_NULL_ACCOUNT"] = STEEMIT_NULL_ACCOUNT;
            result["STEEMIT_NUM_INIT_MINERS"] = STEEMIT_NUM_INIT_MINERS;
            result["STEEMIT_PROXY_TO_SELF_ACCOUNT"] = STEEMIT_PROXY_TO_SELF_ACCOUNT;
            result["STEEMIT_SECONDS_PER_YEAR"] = STEEMIT_SECONDS_PER_YEAR;
            result["STEEMIT_REVERSE_AUCTION_WINDOW_SECONDS"] = STEEMIT_REVERSE_AUCTION_WINDOW_SECONDS;
            result["STEEMIT_TEMP_ACCOUNT"] = STEEMIT_TEMP_ACCOUNT;
            result["STEEMIT_UPVOTE_LOCKOUT"] = STEEMIT_UPVOTE_LOCKOUT;
            result["STEEMIT_VESTING_WITHDRAW_INTERVALS"] = STEEMIT_VESTING_WITHDRAW_INTERVALS;
            result["STEEMIT_VESTING_WITHDRAW_INTERVAL_SECONDS"] = STEEMIT_VESTING_WITHDRAW_INTERVAL_SECONDS;
            result["STEEMIT_VOTE_REGENERATION_SECONDS"] = STEEMIT_VOTE_REGENERATION_SECONDS;
            result["STEEM_SYMBOL"] = STEEM_SYMBOL;
            result["VESTS_SYMBOL"] = VESTS_SYMBOL;
            result["BLOCKCHAIN_NAME"] = BLOCKCHAIN_NAME;
            result["STEEMIT_ADDRESS_PREFIX"] = STEEMIT_ADDRESS_PREFIX;

            return result;
        }

    }
} // golos::protocol